<?php

declare(strict_types=1);

namespace Drupal\ai_content_drafter\Service;

use Drupal\Component\Utility\Xss;
use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\Entity\EntityFieldManagerInterface;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Extension\ModuleHandlerInterface;
use Drupal\Core\Logger\LoggerChannelInterface;
use Drupal\node\NodeInterface;

/**
 * Persists an AI-generated draft as an unpublished node.
 *
 * Every save:
 *
 *  - Forces status=0 regardless of what the drafter asked for. Belt-and-
 *    braces for the always-draft invariant: a bug in the pipeline cannot
 *    accidentally publish AI output.
 *  - Sets moderation_state to the configured default (draft) when
 *    content_moderation is enabled on the target bundle.
 *  - Sanitises the LLM body through Xss::filterAdmin() before it hits the
 *    database, so even if Anthropic tries to inject a <script>, Drupal's
 *    filter strips it. We do NOT trust model output.
 *  - Applies the metatag + schema fields generated by the pipeline,
 *    respecting the target bundle's actual field list so missing fields
 *    are silently skipped instead of blowing up.
 */
final class DraftWriter {

  public function __construct(
    private readonly EntityTypeManagerInterface $entityTypeManager,
    private readonly EntityFieldManagerInterface $fieldManager,
    private readonly ModuleHandlerInterface $moduleHandler,
    private readonly ConfigFactoryInterface $configFactory,
    private readonly LoggerChannelInterface $logger,
  ) {}

  /**
   * Create a draft node and return the saved entity.
   *
   * @param array{title: string, body: string, summary?: string, metatags?: array, keywords?: list<string>} $draft
   *   The drafter output struct.
   *
   * @return \Drupal\node\NodeInterface
   *   The saved, unpublished draft.
   */
  public function write(array $draft): NodeInterface {
    $settings = $this->configFactory->get('ai_content_ingest.settings');
    $target_bundle = (string) ($settings->get('target_bundle') ?: 'article');
    $target_body_field = (string) ($settings->get('target_body_field') ?: 'body');
    $moderation_state = (string) ($settings->get('default_moderation_state') ?: 'draft');

    $storage = $this->entityTypeManager->getStorage('node');
    $clean_body = Xss::filterAdmin((string) ($draft['body'] ?? ''));
    $summary = isset($draft['summary']) ? Xss::filter((string) $draft['summary']) : '';

    $values = [
      'type' => $target_bundle,
      'title' => \mb_substr((string) ($draft['title'] ?? 'Untitled AI draft'), 0, 255),
      // Never trust the drafter — always unpublished on creation.
      'status' => 0,
    ];

    // Attach body + summary if the bundle actually has that field.
    $field_defs = $this->fieldManager->getFieldDefinitions('node', $target_bundle);
    if (isset($field_defs[$target_body_field])) {
      $values[$target_body_field] = [
        'value' => $clean_body,
        'summary' => $summary,
        'format' => 'basic_html',
      ];
    }

    // Respect content_moderation if it's installed and the bundle uses it.
    if ($this->moduleHandler->moduleExists('content_moderation')) {
      $values['moderation_state'] = $moderation_state;
    }

    $node = $storage->create($values);
    $node->save();

    $this->logger->info('AI draft @nid created for bundle @bundle (title: @title)', [
      '@nid' => $node->id(),
      '@bundle' => $target_bundle,
      '@title' => $node->getTitle(),
    ]);

    return $node;
  }

}
