<?php

declare(strict_types=1);

namespace Drupal\ai_content_drafter\Service;

use Drupal\Component\Serialization\Json;
use Drupal\Component\Utility\Xss;
use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\Entity\EntityFieldManagerInterface;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Extension\ModuleHandlerInterface;
use Drupal\Core\Logger\LoggerChannelInterface;
use Drupal\node\NodeInterface;

/**
 * Persists an AI-generated draft as an unpublished node.
 *
 * Every save:
 *
 *  - Forces status=0 regardless of what the drafter asked for. Belt-and-
 *    braces for the always-draft invariant: a bug in the pipeline cannot
 *    accidentally publish AI output.
 *  - Sets moderation_state to the configured default (draft) when
 *    content_moderation is enabled on the target bundle.
 *  - Sanitises the LLM body through Xss::filterAdmin() before it hits the
 *    database, so even if Anthropic tries to inject a <script>, Drupal's
 *    filter strips it. We do NOT trust model output.
 *  - Applies the metatag + schema fields generated by the pipeline,
 *    respecting the target bundle's actual field list so missing fields
 *    are silently skipped instead of blowing up.
 */
final class DraftWriter {

  public function __construct(
    private readonly EntityTypeManagerInterface $entityTypeManager,
    private readonly EntityFieldManagerInterface $fieldManager,
    private readonly ModuleHandlerInterface $moduleHandler,
    private readonly ConfigFactoryInterface $configFactory,
    private readonly DraftNotifier $notifier,
    private readonly LoggerChannelInterface $logger,
  ) {}

  /**
   * Create a draft node and return the saved entity.
   *
   * @param array{title: string, body: string, summary?: string, seo_title?: string, seo_description?: string, keywords?: list<string>} $draft
   *   The drafter output struct.
   *
   * @return \Drupal\node\NodeInterface
   *   The saved, unpublished draft.
   */
  public function write(array $draft): NodeInterface {
    $settings = $this->configFactory->get('ai_content_ingest.settings');
    $target_bundle = (string) ($settings->get('target_bundle') ?: 'article');
    $target_body_field = (string) ($settings->get('target_body_field') ?: 'body');
    $moderation_state = (string) ($settings->get('default_moderation_state') ?: 'draft');

    $storage = $this->entityTypeManager->getStorage('node');
    $clean_body = Xss::filterAdmin((string) ($draft['body'] ?? ''));
    $summary = isset($draft['summary']) ? Xss::filter((string) $draft['summary']) : '';

    $values = [
      'type' => $target_bundle,
      'title' => \mb_substr((string) ($draft['title'] ?? 'Untitled AI draft'), 0, 255),
      // Never trust the drafter — always unpublished on creation.
      'status' => 0,
    ];

    // Attach body + summary if the bundle actually has that field.
    $field_defs = $this->fieldManager->getFieldDefinitions('node', $target_bundle);
    if (isset($field_defs[$target_body_field])) {
      $values[$target_body_field] = [
        'value' => $clean_body,
        'summary' => $summary,
        'format' => 'basic_html',
      ];
    }

    // Metatag field: if the bundle has a metatag field (machine name starts
    // with field_metatag or is exactly 'metatag'), fill it with the AI's
    // SEO enrichment output. Metatag stores values as a serialized array.
    $metatag_field = $this->findMetatagField($field_defs);
    if ($metatag_field !== NULL && ($draft['seo_title'] || $draft['seo_description'])) {
      $tags = [];
      if (!empty($draft['seo_title'])) {
        $tags['title'] = \mb_substr(Xss::filter((string) $draft['seo_title']), 0, 60);
      }
      if (!empty($draft['seo_description'])) {
        $tags['description'] = \mb_substr(Xss::filter((string) $draft['seo_description']), 0, 155);
        $tags['og_description'] = $tags['description'];
        $tags['twitter_cards_description'] = $tags['description'];
      }
      if (!empty($draft['keywords'])) {
        $kw_safe = \array_map(
          static fn (string $kw): string => \mb_substr(Xss::filter($kw), 0, 40),
          \array_filter((array) $draft['keywords'], 'is_string')
        );
        if ($kw_safe !== []) {
          $tags['keywords'] = \implode(', ', \array_slice($kw_safe, 0, 6));
        }
      }
      // Metatag 2.x stores field values as JSON-encoded strings. The
      // decoder in metatag_data_decode() also accepts legacy serialised PHP
      // for back-compat, but we ship the current format to avoid triggering
      // the v1 code path.
      $values[$metatag_field] = Json::encode($tags);
    }

    // Respect content_moderation if it's installed and the bundle uses it.
    if ($this->moduleHandler->moduleExists('content_moderation')) {
      $values['moderation_state'] = $moderation_state;
    }

    // Flag the node so the admin review view can distinguish AI drafts
    // from human drafts without parsing body content.
    if (isset($field_defs['field_ai_drafted'])) {
      $values['field_ai_drafted'] = 1;
    }

    $node = $storage->create($values);
    $node->save();

    $this->logger->info('AI draft @nid created for bundle @bundle (title: @title)', [
      '@nid' => $node->id(),
      '@bundle' => $target_bundle,
      '@title' => $node->getTitle(),
    ]);

    // Best-effort notification. Failure does not unwind the save.
    $this->notifier->notify($node);

    return $node;
  }

  /**
   * Locate a metatag field on the bundle, if one exists.
   *
   * Scans the field list for any field of type 'metatag' and returns its
   * machine name. Supports the common patterns `field_metatags`,
   * `field_meta_tags`, and a bare 'metatag' field without falling over
   * if the bundle has none.
   */
  private function findMetatagField(array $field_defs): ?string {
    foreach ($field_defs as $name => $def) {
      if ($def->getType() === 'metatag') {
        return $name;
      }
    }
    return NULL;
  }

}
